#!/bin/bash

gnome-terminal -e 'bash -c "./my-router topology.txt A | tee outputA.txt" & sleep 1;'
gnome-terminal -e 'bash -c "./my-router topology.txt B | tee outputB.txt" & sleep 1;'
gnome-terminal -e 'bash -c "./my-router topology.txt C | tee outputC.txt" & sleep 1;'
gnome-terminal -e 'bash -c "./my-router topology.txt D | tee outputD.txt" & sleep 1;'
gnome-terminal -e 'bash -c "./my-router topology.txt E | tee outputE.txt" & sleep 1;'
gnome-terminal -e 'bash -c "./my-router topology.txt F | tee outputF.txt" & sleep 1;'
